//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serial_Flakes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public int id { get; set; }
        public string device_name { get; set; }
        public string device_code { get; set; }
        public string device_SKU { get; set; }
        public string device_description { get; set; }
        public string device_pic { get; set; }
    }
}
